### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by yannhan** [HawkAaron/mxnet-transducer#2]
AttributeError: module 'mxnet.ndarray.contrib' has no attribute 'RNNTLoss'

**Comment by HawkAaron** [comment]
@hsama95 
Have you built this with mxnet source code ?
Please follow the instructions [here](https://github.com/HawkAaron/mxnet-transducer#install-and-test).

**Comment by yannhan** [comment]
Yes, I built, and I have added the python API to mxnet/gluon/loss.py

**Comment by hsama95** [comment]
I am also little confused about the function of incubator-mxnet. Just downloaded and did nothing?

**Comment by yannhan** [comment]
I reinstalled again. The test.py passed, but I didn't find the path to mxnet/gluon/loss.py to add python API. Does it matter?
